### PR TITLE
TUT4T

### PR DESCRIPTION
**Pull request by alexmgns**
1. Since both H0 and especially p-value will be new/relatively new I have two short 4, and 3 minute videos respectively introducing the concepts. This will help minimize the delta in explanation quality between tutorial groups and in general I found the videos to be very high quality, maybe the p-value video can end at 2:40, but also maybe the last 40 seconds are useful to reinforce some concepts.
2. When introducing bootstrap simulation code there is the option of having the TA explain the code, or explaining the creation of the code using a GPT log? I have left both options in the TUT for now. 
3. 65 minutes of the tutorial are being used on h0 + pvalue and 55 minutes on review. Without having taught this topic before I am unsure if 65 minutes is a good amount of time to be able to convey the concepts? Maybe I need to re-iterate some points more/allow more time?
4. For now I have TA lead review first and then group separated/lead review second, this seems natural for me but it could also be flipped.
5. In F23 TUT you introduced differences in H0 assumptions based on sample distrubution, this seems maybe too much to ask for a first introduction of the concept, I for one have no recollection of that introduction even happening, I have put it at the very end party for this reason, but also because I didnt want the communication section to be at the end for fear of the last 1-2 groups being cut off during their presentation due to time.

### CODE REVIEW

**Comment by alexmgns** [comment]
One more comment, homework, I have no opinion on whether or not there should be a homework with this tutorial. It is always nice when there is no homework before an exam however, but also, homework before an exam is exam prep so im not sure, maybe I can write some template GPT questions to help students "explore/revise" for the midterm.

**Review by pointOfive — APPROVED** [review]
New files -- pulling in to review and will rename

**Comment by pointOfive** [comment]
### replies to above points

1. I think the videos are good ("in general I found the videos to be very high quality" -- agreed); but, they should be moved to pre-lecture videos: the TA should take the role of videos -- I don't want TUT to just be showing videos to students that they can watch on their own time. TUT is the personal human interaction presentation of these topics, and then the videos should clarify and reinforce the conversation and discussion from TUT 
 
    1. "This will help minimize the delta in explanation quality between tutorial groups" -- you're not wrong and it's a reasonable idea; but, we still achieve this as pre-lecture videos

2. I address this with an extensive reflection on the course overall all (below). I'll leave it to you to decide what your returned revision to me looks like for the next round, and I'll review it from there once I see what you've gone with and how that flows (if you've changed it.

    1. You have limited time... 20 minutes review + 40 minutes demo + 40 minutes (down from 50) to address the Stella problem and make a communication exercise out of it... if you're going to add some ChatGPT interaction make sure you think it's achievable under any time outlines you're suggesting

3. We'll have 100 (not 120) minutes for TUT for 10 after starts and 10 minute break allowance. I agree time considerations are relevant, but it's looking feasible to me (after what I'm suggesting moving to prefecture/lecture material, as you'll see below).

4. I must have not read far enough to see / understand how this will work. My feedback for what you'll work on below includes something that essentially says "I've not seen what your communication activity looks like here -- revise that to fit into the updated time frame and under the **strong recommendation** that you drop considerations of 'theoretical'/'parametric' etc... this is looking like substantial content creep material bloat relative to the available time and the newness of these topics (as you note)"

5. Ah, yep -- agreed exactly -- this is my point above.  Actually, my vision for one sample hypothesis stuff is that we do not address 'theoretical'/'parametric' (and eventually nonparametric tests) this time around... this is, since, as you say... the overall newness and challenge of these topics is a lot even without this...

    1. In TUT4 demo you'll see that I do plot theoretical sampling distributions (which are derived via CLT); but, my point with this is not to explain this or address this topic in detail with the students; rather, to show that bootstrapping (and other sampling methods) work [according to some theoretical result]; so, they are to emphasize the sampling based materials we have.
    
    2. I sat and thought for a little bit if introducing the 'theoretical'/'parametric' stuff here in a similar way would be useful; and, I don't think so, at least not for TUT. Maybe I'll think about this again when it comes to LEC, but my LEC plans involve revisiting and reviewing all these topics again, which I don't think will be "helpfully repetitive while not being unnecessarily repetitive"; so, it's unlikely that I'll be able to spend much time on 'theoretical'/'parametric' (and eventually nonparametric tests) this time around.
    
    3. The video Ali introduces in week 4 raises the idea of "+/- 2 SE" confidence intervals, which are "theoretically derived", so I'm not in principle opposed to introducing this kind of content as a way to bring into sharp relief by way of contrast the sampling based methods that we're focussed on in STA130; but, this is happening in the homework, and it's guided by ChatGPT, so it's more of a "use homework to tackle new ideas and problems" which is my preferred use of homework...
    
    4. which, by the way, is something that could be disagreed about... classical math homework has you practice the same things you learn in class over and over... but my feeling is this "rinse, wash, repeat" style of "learning methods" is outdated, and it's a much better use of student time to tackle problems that push the boundaries of their thinking by extending the scope of the problems they're looking at and working on... definitely a point for conversation though, as we go through the homework activities we define; and, especially relevant here, as you've not yet built the homework activity for this week (since we've been unclear about where and what it was actually going to be)... so the philosophy here is definitely something worth thinking about...

Given the reschedule adjustment to push the midterm back a week, we'll want a homework here after all; so, as I direct below, please put that together and then I'll do a final review of the full revision of the TUT you get back to me based on my feedback here

### editing comments

1. I like building on the vaccine data project in tutorial; but, the new demo now shows a two sample bootstrap, which does not align with the style of data discussed in the week 4 video introduced by Ali

    1. I've adjusted this, but I've decided not to add a hint into the prompt into week 4 to guide students towards this approach
    
        1.  Is this something that we should consider doing? I kind of like that students might not think to do this on the homework and then would see the that it can be done as part of TUT5... I think that would be an impactful "ah ha!" learning experience? 
        
    2. That is, Ali's data implicitly suggests a paired samples test which is a one sample test, and I like this as a way to begin hypothesis testing, but it seems this needs to be more explicit
    
    3. I see that you do use the paired sample difference below for the hypothesis test, which is good; but, you're conflating bootstrapping with parametric sampling, and not actually taking advantage of the paired sampling structure
    
        1. I've adjusted this
        
2. I've adjusted the hypothesis statement in TUT5, and I've gone back and adjusted week 4 as well to better address the concern here

3. I like the vaccine data idea (and indeed it's proving to be a very productive segment across weeks 4/5), but there's also the happiness data study (about journaling and gratitude)... should we consider using that for this "project" instead? Then there's some extra material to make the problem space a little richer and it gets people thinking about some mental health and happiness stuff... which I always think is good to do...

    1. I might be wrong that this is before/after data now that I think about it... so not actually a paired samples study... but we should double check that... maybe there are before and after scores within treatment conditions
    
4. The videos content are both great choices

5. I didn't personally prefer the suggested changes https://chatgpt.com/share/35deb6ea-14a2-4903-ae2b-b4d655192745; but, ...

    1. if you want to consider this again based on my revised changes, I'm definitely open to this kind of idea
    
    2. It seems to me that demonstrating the capabilities of Chat3.5(+) is shaping up to be a big part of what this course now is... e.g., based on what it can do in terms of making figures for you, the necessary skill set has drastically shifted when it comes to visualizing data... people don't need to know how to make figures themselves anymore for baseline plotly/seaborn/matplotlib like functionality... so, for STA130 graduates to be competitive coming out of this class, they need to be able to use ChatGPT/etc to produce what they need... here, we're talking about the ability of ChatGPT to run a null hypothesis simulation experiment... perhaps this too is something that analysts now offload to Chat... not sure about this... it's simple enough to just do it yourself, once you have the idea (compared to making figures, which takes A LOT of time); but, anyway, hopefully you get my point... we should be INJECTING Chat into anything where it makes sense to improves productivity/efficiency.

### Requested Next Steps

1. review my feedback and then send in another PR update with your revisions addressing everything

2. I'm feeling good about everything up to the communication section

    1. FIRST review https://github.com/pointOfive/STA130_ChatGPT/blob/main/TUT/STA130F24_TUT03_Sep20.ipynb and THEN https://github.com/pointOfive/STA130_ChatGPT/blob/main/TUT/STA130F24_TUT04_Sep27.ipynb to see the outline structure that's being followed

3. As things currently stand, you have 40 minute for the communication activity

    1. Rework this into what your suggested "finalized" form is, with the conversation about 'theoretical'/'parametric' (from above) in mind.  I wrote my thoughts there first so I'll not repeat them here; but, scope/content creep/material bloat is definitely an issue here (and I think we agree that we should address it decisively and with prejudice) 
    2. You have commented on your considerations for organizing this not necessarily feeling clear; but, I encourage you to make the decision you feel best, and I'll take it from there
    
4. Then we need a HW, as this is now just a "normal sequence for week 5" with the updated scheduling

    1. I haven't responded generally to the group on slack about this yet; but, after thinking about it, this time around I'm not going to follow CS with 3/4-week cycles and multiple midterms. I will eventually raise this idea wth the other STA130 profs; but, I think moving to this framework would require a broader shift across all versions of the course than just mine
    
    2. My personal motivation regarding was driven by a desire to place midterms away from other courses; so, moving it earlier towards students CS midterms defeats the purpose of having it earlier; and, I think the scheduling change we've made is for the best after all conversations I've had about this (including discussing the earlier midterm date with other STA130 profs)
    
    3. Anyway, TUT3 and TUT4 will give you good examples for what the HW here should look like.
    
5. Type of errors (alpha/beta I/II) -- move this material to the LEC. I like it a lot, but it doesn't belong in TUT as I now view the scope of TUT and essentially addressing getting p-values in a simulation based manner for the Stella problem (with the follow up on the vaccine data being a good precursor to this; and the move to coin flipping from the "assumed normality" of the vaccine data problem being "enough of a shift/expansion" of scope)

    1. I'll see what you do with your HW draft, and I do have some comments about what I think the philosophy of the HW should be; but, my suggestion here would be to give students another "Stella-like problem" in the form of a project assignment like Ali made for the Week 4 HW as the Postlecture homework, with the Prelecture homework being whatever questions you think it would be good for students to review and think about before coming to class to listen to me talk about "p-values under the null" (and the errors above, and whatever other suggestions you might imagine for a week 5 LEC on hypothesis testing for one sample... speaking of which... there's a "left/right" kissing example which I'll probably use for my LEC...)
    
6. I've got you started with the structure for "Prelecture HW" in the notebook updates I've sent back, but follow TUT3/4 for the structure of the HW if you're unfamiliar with what I'm looking for in terms of structure

7. I've left the MT review with ChatGPT at the bottom of the notebook for now.  You can leave that there for now and leave building that up to me, unless you get excited about making that to support the Friday Oct 11 TUT which will be a review for the Friday Oct 18 midterm

**Comment by pointOfive** [comment]
Will give LEC another look and respond with any additional comments that might be needed beyond my previous comment that "I'll look at this and plan to finalize it's design relative to the final version of the TUT once I have that".

- In general, I'm not spending time on making/finalizing my lectures right now... they will take the lead of the materials we outline through the TUTs (and homeworks)... so I'm planning to hammer those out very quickly whenever everything else has settled down into the final form.

**Pull request merged**
